/**
 * Created by doola on 9/20/2016.
 */
var MOVIE_DATA = [
    {
        "Title": "Suicide Squad",
        "Year": "2016",
        "Rated": "PG-13",
        "Released": "05 Aug 2016",
        "Runtime": "123 min",
        "Genre": "Action, Adventure, Crime",
        "Director": "David Ayer",
        "Writer": "David Ayer",
        "Actors": "Will Smith, Jaime FitzSimons, Ike Barinholtz, Margot Robbie",
        "Plot": "A secret government agency recruits some of the most dangerous incarcerated criminals to form a defensive task force, with their first case leading to a potential apocalypse.",
        "Language": "English, Japanese, Spanish",
        "Country": "USA",
        "Awards": "2 wins & 3 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjM1OTMxNzUyM15BMl5BanBnXkFtZTgwNjYzMTIzOTE@._V1_SX300.jpg",
        "Metascore": "40",
        "imdbRating": "6.7",
        "imdbVotes": "201,519",
        "imdbID": "tt1386697",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "Blair Witch",
        "Year": "2016",
        "Rated": "R",
        "Released": "16 Sep 2016",
        "Runtime": "89 min",
        "Genre": "Horror, Thriller",
        "Director": "Adam Wingard",
        "Writer": "Simon Barrett",
        "Actors": "James Allen McCune, Corbin Reid, Wes Robinson, Valorie Curry",
        "Plot": "After discovering a video showing what he believes to be his sister's experiences in the demonic woods of the Blair Witch, James and a group of friends head to the forest in search of his lost sibling.",
        "Language": "English",
        "Country": "USA",
        "Awards": "N/A",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjI0NTEyMjA3NV5BMl5BanBnXkFtZTgwODk5OTU4OTE@._V1_SX300.jpg",
        "Metascore": "N/A",
        "imdbRating": "N/A",
        "imdbVotes": "N/A",
        "imdbID": "tt1540011",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "The Shallows",
        "Year": "2016",
        "Rated": "PG-13",
        "Released": "24 Jun 2016",
        "Runtime": "86 min",
        "Genre": "Drama, Horror, Thriller",
        "Director": "Jaume Collet-Serra",
        "Writer": "Anthony Jaswinski",
        "Actors": "Blake Lively, Óscar Jaenada, Brett Cullen, Sedona Legge",
        "Plot": "A mere 200 yards from shore, surfer Nancy is attacked by a great white shark, with her short journey to safety becoming the ultimate contest of wills.",
        "Language": "English, Spanish",
        "Country": "USA",
        "Awards": "1 nomination.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjA1MTA4MzU4Ml5BMl5BanBnXkFtZTgwNjUxNjczODE@._V1_SX300.jpg",
        "Metascore": "59",
        "imdbRating": "6.6",
        "imdbVotes": "21,966",
        "imdbID": "tt4052882",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "X-Men: Apocalypse",
        "Year": "2016",
        "Rated": "PG-13",
        "Released": "27 May 2016",
        "Runtime": "144 min",
        "Genre": "Action, Adventure, Sci-Fi",
        "Director": "Bryan Singer",
        "Writer": "Simon Kinberg (screenplay), Bryan Singer (story), Simon Kinberg (story), Michael Dougherty (story), Dan Harris (story)",
        "Actors": "James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult",
        "Plot": "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
        "Language": "English, Polish, German, Arabic, Egyptian (Ancient)",
        "Country": "USA",
        "Awards": "2 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjU1ODM1MzYxN15BMl5BanBnXkFtZTgwOTA4NDE2ODE@._V1_SX300.jpg",
        "Metascore": "52",
        "imdbRating": "7.3",
        "imdbVotes": "156,549",
        "imdbID": "tt3385516",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "Captain America: Civil War",
        "Year": "2016",
        "Rated": "PG-13",
        "Released": "06 May 2016",
        "Runtime": "147 min",
        "Genre": "Action, Adventure, Sci-Fi",
        "Director": "Anthony Russo, Joe Russo",
        "Writer": "Christopher Markus (screenplay), Stephen McFeely (screenplay), Joe Simon (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)",
        "Actors": "Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan",
        "Plot": "Political interference in the Avengers' activities causes a rift between former allies Captain America and Iron Man.",
        "Language": "English, German, Xhosa, Russian, Romanian",
        "Country": "USA, Germany",
        "Awards": "2 wins & 7 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_SX300.jpg",
        "Metascore": "75",
        "imdbRating": "8.2",
        "imdbVotes": "285,911",
        "imdbID": "tt3498820",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "Snowden",
        "Year": "2016",
        "Rated": "R",
        "Released": "16 Sep 2016",
        "Runtime": "134 min",
        "Genre": "Biography, Drama, Thriller",
        "Director": "Oliver Stone",
        "Writer": "Kieran Fitzgerald (screenplay), Oliver Stone (screenplay), Anatoly Kucherena (book), Luke Harding (book)",
        "Actors": "Shailene Woodley, Scott Eastwood, Nicolas Cage, Joseph Gordon-Levitt",
        "Plot": "NSA employee Edward Snowden leaks thousands of classified documents to the press.",
        "Language": "English",
        "Country": "USA, Germany, France",
        "Awards": "N/A",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMTg2MzYzNzgzOF5BMl5BanBnXkFtZTgwOTg4NzQ4OTE@._V1_SX300.jpg",
        "Metascore": "N/A",
        "imdbRating": "5.9",
        "imdbVotes": "535",
        "imdbID": "tt3774114",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "Deadpool",
        "Year": "2016",
        "Rated": "R",
        "Released": "12 Feb 2016",
        "Runtime": "108 min",
        "Genre": "Action, Adventure, Comedy",
        "Director": "Tim Miller",
        "Writer": "Rhett Reese, Paul Wernick, Fabian Nicieza (character), Rob Liefeld (character)",
        "Actors": "Ryan Reynolds, Karan Soni, Ed Skrein, Michael Benyaer",
        "Plot": "A former Special Forces operative turned mercenary is subjected to a rogue experiment that leaves him with accelerated healing powers, adopting the alter ego Deadpool.",
        "Language": "English",
        "Country": "USA",
        "Awards": "4 wins & 11 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjQyODg5Njc4N15BMl5BanBnXkFtZTgwMzExMjE3NzE@._V1_SX300.jpg",
        "Metascore": "65",
        "imdbRating": "8.1",
        "imdbVotes": "494,016",
        "imdbID": "tt1431045",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "The Godfather",
        "Year": "1972",
        "Rated": "R",
        "Released": "24 Mar 1972",
        "Runtime": "175 min",
        "Genre": "Crime, Drama",
        "Director": "Francis Ford Coppola",
        "Writer": "Mario Puzo (screenplay), Francis Ford Coppola (screenplay), Mario Puzo (novel)",
        "Actors": "Marlon Brando, Al Pacino, James Caan, Richard S. Castellano",
        "Plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "Language": "English, Italian, Latin",
        "Country": "USA",
        "Awards": "Won 3 Oscars. Another 23 wins & 27 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BMjEyMjcyNDI4MF5BMl5BanBnXkFtZTcwMDA5Mzg3OA@@._V1_SX300.jpg",
        "Metascore": "100",
        "imdbRating": "9.2",
        "imdbVotes": "1,161,579",
        "imdbID": "tt0068646",
        "Type": "movie",
        "Response": "True"
    },
    {
        "Title": "The Italian Job",
        "Year": "2003",
        "Rated": "PG-13",
        "Released": "30 May 2003",
        "Runtime": "111 min",
        "Genre": "Action, Crime, Thriller",
        "Director": "F. Gary Gray",
        "Writer": "Troy Kennedy-Martin, Donna Powers (screenplay), Wayne Powers (screenplay)",
        "Actors": "Mark Wahlberg, Charlize Theron, Donald Sutherland, Jason Statham",
        "Plot": "After being betrayed and left for dead in Italy, Charlie Croker and his team plan an elaborate gold heist against their former ally.",
        "Language": "English, Russian, Italian",
        "Country": "USA, France, UK",
        "Awards": "7 wins & 7 nominations.",
        "Poster": "http://ia.media-imdb.com/images/M/MV5BNDYyNzYxNjYtNmYzMC00MTE0LWIwMmYtNTAyZDBjYTIxMTRhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
        "Metascore": "68",
        "imdbRating": "7.0",
        "imdbVotes": "287,148",
        "imdbID": "tt0317740",
        "Type": "movie",
        "Response": "True"
    }
];
